language: php

php:
  - 5.3.3
  - 5.4
  - 5.5

env:
  - MONGO_VERSION=1.2.12

services: mongodb

before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

script:
  - vendor/bin/phpunit

